version: "3.8"

services:
  instabasic:
    build: ./instabasic
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./instabasic/:/usr/src/app/
    ports:
      - 8080:8000
    env_file: 
      - ./instabasic/.dev.env
    depends_on: 
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=instabasic
      - POSTGRES_PASSWORD=instabasic
      - POSTGRES_DB=instabasic_dev
    
volumes: 
  postgres_data: